server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar?serverTimeZone=ADT
    username: postgres
    password: 512817
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
    pathsToMatch: /api/**
    swagger-ui:
      use-root-path: true

