insert into customers (first_name, last_name, city) values ('Gerek', 'Wooster', 'Krebet');
insert into customers (first_name, last_name, city) values ('Cleopatra', 'Heater', 'Truskolasy');
insert into customers (first_name, last_name, city) values ('Marinna', 'Wheelband', 'Bajia');
insert into customers (first_name, last_name, city) values ('Franklyn', 'Darmody', 'Foz Sousa');
insert into customers (first_name, last_name, city) values ('Rockwell', 'Casa', 'Telhado');
insert into customers (first_name, last_name, city) values ('Velma', 'Lewerenz', 'Thị Trấn Mỹ Lộc');
insert into customers (first_name, last_name, city) values ('Roxanne', 'Owlner', 'Larvik');
insert into customers (first_name, last_name, city) values ('Cornelia', 'Gheerhaert', 'Kilkenny');
insert into customers (first_name, last_name, city) values ('Pyotr', 'Tilling', 'Jacksonville');
insert into customers (first_name, last_name, city) values ('Rozella', 'Extance', 'Mababanaba');
insert into customers (first_name, last_name, city) values ('Gaby', 'Bromige', 'Gelsenkirchen');
insert into customers (first_name, last_name, city) values ('Hermine', 'Swaton', 'Veselí nad Lužnicí');
insert into customers (first_name, last_name, city) values ('Gerrard', 'Ogborne', 'Lojejerkrajan');
insert into customers (first_name, last_name, city) values ('Duncan', 'Emmens', 'Weitang');
insert into customers (first_name, last_name, city) values ('Michaelina', 'Piletic', 'Sanhu');
insert into customers (first_name, last_name, city) values ('Rudy', 'Batchelour', 'Komsomol’skiy');
insert into customers (first_name, last_name, city) values ('Fianna', 'Feltoe', 'Guangdu');
insert into customers (first_name, last_name, city) values ('Erl', 'Fassmann', 'Dapdap');
insert into customers (first_name, last_name, city) values ('Laurens', 'Zannelli', 'Bangrat');
insert into customers (first_name, last_name, city) values ('Jodee', 'Jansie', 'Dayr as Sūdān');
insert into customers (first_name, last_name, city) values ('Gilberto', 'Broadbridge', 'Huaniao');
insert into customers (first_name, last_name, city) values ('Bale', 'Clive', 'Binjiang');
insert into customers (first_name, last_name, city) values ('Coral', 'Pettigrew', 'Kuala Lumpur');
insert into customers (first_name, last_name, city) values ('Denys', 'Schole', 'Kedungtulup');
insert into customers (first_name, last_name, city) values ('Marcelline', 'MacGahey', 'San Pedro de Lloc');
insert into customers (first_name, last_name, city) values ('Frayda', 'Stroulger', 'Sulyukta');
insert into customers (first_name, last_name, city) values ('Lisetta', 'Cahillane', 'Cergy-Pontoise');
insert into customers (first_name, last_name, city) values ('Linell', 'Cottrill', 'Machetá');
insert into customers (first_name, last_name, city) values ('Morey', 'Tweed', 'Sakon Nakhon');
insert into customers (first_name, last_name, city) values ('Fran', 'Wemes', 'Banyuresmi');
insert into customers (first_name, last_name, city) values ('Zarla', 'Ghiroldi', 'Jönköping');
insert into customers (first_name, last_name, city) values ('Cinda', 'Rowell', 'Ouango');
insert into customers (first_name, last_name, city) values ('Berna', 'Waltho', 'Bali');
insert into customers (first_name, last_name, city) values ('Boniface', 'Spykins', 'Mulan');
insert into customers (first_name, last_name, city) values ('Crista', 'Ploughwright', 'Coihaique');
insert into customers (first_name, last_name, city) values ('Brittaney', 'Daid', 'Ulaanbaatar');
insert into customers (first_name, last_name, city) values ('Waylin', 'Rabbatts', 'Xikou');
insert into customers (first_name, last_name, city) values ('Roderic', 'Trenfield', 'Çepan');
insert into customers (first_name, last_name, city) values ('Phillip', 'McGreary', 'Betafo');
insert into customers (first_name, last_name, city) values ('Nanni', 'Woolhouse', 'Chok Chai');
insert into customers (first_name, last_name, city) values ('Bridgette', 'Lambdin', 'Taclobo');
insert into customers (first_name, last_name, city) values ('Hyacinthie', 'Tucknott', 'Vidoši');
insert into customers (first_name, last_name, city) values ('Catrina', 'Dy', 'Fukuchiyama');
insert into customers (first_name, last_name, city) values ('Seamus', 'Gebuhr', 'Trollhättan');
insert into customers (first_name, last_name, city) values ('Sayres', 'Scothron', 'Liliongan');
insert into customers (first_name, last_name, city) values ('Duane', 'Burstow', 'Cilegi');
insert into customers (first_name, last_name, city) values ('Wenona', 'Wherton', 'Louriceira');
insert into customers (first_name, last_name, city) values ('Blair', 'Baine', 'San Matías');
insert into customers (first_name, last_name, city) values ('Carolan', 'Chanson', 'Tawangsari');
insert into customers (first_name, last_name, city) values ('Jamill', 'Lesor', 'Peuteuy');