insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Flex', 'Ford', 2013, 2014);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Land Cruiser', 'Toyota', 2004, 2005);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Edge', 'Ford', 2008, 2009);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Tundra', 'Toyota', 2008, 2009);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Forenza', 'Suzuki', 2008, 2009);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('STS', 'Cadillac', 2011, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Colorado', 'Chevrolet', 2010, 2010);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Envoy XL', 'GMC', 2002, 2002);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Phantom', 'Rolls-Royce', 2009, 2010);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('XJ', 'Jaguar', 2011, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Capri', 'Mercury', 1986, 1987);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Rodeo', 'Isuzu', 1996, 1996);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('TT', 'Audi', 2005, 2006);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Caprice Classic', 'Chevrolet', 1995, 1996);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Daewoo Lacetti', 'Suzuki', 2007, 2008);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('IPL G', 'Infiniti', 2011, 2011);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Corvette', 'Chevrolet', 1963, 1963);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Seville', 'Cadillac', 1994, 1994);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Fit', 'Honda', 2012, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('ES', 'Lexus', 1996, 1997);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('LR4', 'Land Rover', 2011, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Sonoma', 'GMC', 1999, 1999);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('S10', 'Chevrolet', 1999, 2000);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Esprit', 'Lotus', 1998, 1999);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('LS', 'Lincoln', 2000, 2001);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('New Yorker', 'Chrysler', 1993, 1994);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Sonata', 'Hyundai', 2011, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('X3', 'BMW', 2010, 2011);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Savana 2500', 'GMC', 2005, 2005);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Tahoe', 'Chevrolet', 1999, 2000);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('X-Type', 'Jaguar', 2004, 2005);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Previa', 'Toyota', 1994, 1995);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Grand Am', 'Pontiac', 1985, 1986);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Continental', 'Lincoln', 2000, 2000);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Dakota', 'Dodge', 2000, 2000);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Grand Am', 'Pontiac', 1991, 1992);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Capri', 'Mercury', 1993, 1994);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Ranger', 'Ford', 1988, 1989);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Exige', 'Lotus', 2010, 2011);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('V8 Vantage S', 'Aston Martin', 2011, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Silverado 1500', 'Chevrolet', 2006, 2006);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Cavalier', 'Chevrolet', 1996, 1996);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('240SX', 'Nissan', 1995, 1995);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('LR2', 'Land Rover', 2012, 2012);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('NSX', 'Acura', 2004, 2004);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('C8', 'Spyker', 2007, 2008);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Murciélago', 'Lamborghini', 2007, 2008);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Firefly', 'Pontiac', 1985, 1986);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Civic', 'Honda', 1994, 1995);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Escort', 'Ford', 1991, 1992);